module Ecm::CoreInfo
  class GemSerializer < ActiveModel::Serializer
    attributes :authors,
               :autorequire,
               :bindir,
               :cert_chain,
               :date,
               :dependencies,
               :description,
               :email,
               :executables,
               :extensions,
               :extra_rdoc_files,
               :files,
               :homepage,
               :licenses,
               :metadata,
               :name,
               :platform,
               :post_install_message,
               :rdoc_options,
               :require_paths,
               :required_ruby_version,
               :required_rubygems_version,
               :requirements,
               :rubyforge_project,
               :rubygems_version,
               :signing_key,
               :specification_version,
               :summary,
               :test_files,
               :version
  end
end
